name: quick-check

on:
  push:
    branches-ignore: [main]

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build container
        run: docker build -t seven-series -f .devcontainer/Dockerfile .
      - name: Build and lint
        run: docker run --rm -v ${{ github.workspace }}:/workspace seven-series bash -c "cd /workspace && make build && make lint"
